# Generated by Django 4.1 on 2025-10-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome'),
        ),
    ]
