# Generated by Django 4.1.13 on 2025-10-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_professor_options_remove_professor_esta_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
    ]
