# Generated by Django 4.1.13 on 2025-10-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='class_name',
            field=models.CharField(default='Aula Desconhecida', max_length=100, verbose_name='Class (Aula)'),
            preserve_default=False,
        ),
    ]
