# Generated by Django 4.1.13 on 2025-10-22 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0003_alter_professor_options_remove_professor_esta_ativo_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_score', models.PositiveSmallIntegerField(default=0, verbose_name='Teaching Score (1-5)')),
                ('punctuality_score', models.PositiveSmallIntegerField(default=0, verbose_name='Punctuality Score (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Review Date')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='teachers.professor', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
