# Generated by Django 4.1.13 on 2025-10-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_aluno_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='curso',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='nome_aluno',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='turma',
            new_name='student_class',
        ),
    ]
